/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics_interface;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author Gabriel
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
    public HomeScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrarClientes = new javax.swing.JMenuItem();
        ListarClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        adicionarProdutoMenuItem = new javax.swing.JMenuItem();
        listarProdutoMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        venderMenuItem = new javax.swing.JMenuItem();
        listaDeVendasMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        fluxoDeCaixajMenuItem = new javax.swing.JMenuItem();
        novoPagamentojMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Cliente");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        CadastrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastrarCliente.png"))); // NOI18N
        CadastrarClientes.setText("Cadastrar");
        CadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarClientes);

        ListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listarCliente.png"))); // NOI18N
        ListarClientes.setText("Listar");
        ListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(ListarClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        adicionarProdutoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastrarProduto.png"))); // NOI18N
        adicionarProdutoMenuItem.setText("Adicionar");
        adicionarProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(adicionarProdutoMenuItem);

        listarProdutoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produtos.png"))); // NOI18N
        listarProdutoMenuItem.setText("Listar");
        listarProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(listarProdutoMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendas");

        venderMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vender.png"))); // NOI18N
        venderMenuItem.setText("Vender");
        venderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(venderMenuItem);

        listaDeVendasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listarProduto.png"))); // NOI18N
        listaDeVendasMenuItem.setText("Lista de Vendas");
        listaDeVendasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeVendasMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(listaDeVendasMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Financeiro");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        fluxoDeCaixajMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/financeiro.png"))); // NOI18N
        fluxoDeCaixajMenuItem.setText("Fluxo de Caixa");
        fluxoDeCaixajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fluxoDeCaixajMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(fluxoDeCaixajMenuItem);

        novoPagamentojMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendas.png"))); // NOI18N
        novoPagamentojMenuItem.setText("Novo Pagamento");
        novoPagamentojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPagamentojMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(novoPagamentojMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClientesActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new JInternalFrame("Cadastrar Cliente");
        jif.setSize(800,650);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        ClienteAdd clienteAdd = new ClienteAdd();
        jif.add(clienteAdd);
        panel.add(jif);
    }//GEN-LAST:event_CadastrarClientesActionPerformed

    public JDesktopPane getPanel() {
        return panel;
    }

    public void setPanel(JDesktopPane panel) {
        this.panel = panel;
    }

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void ListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClientesActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new JInternalFrame("Listar Clientes");
        jif.setSize(800,620);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        ClienteList clienteList = new ClienteList();
        jif.add(clienteList);
        panel.add(jif);
    }//GEN-LAST:event_ListarClientesActionPerformed

    private void adicionarProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutoMenuItemActionPerformed
        JInternalFrame jif = new JInternalFrame("Cadastrar Produtos");
        jif.setSize(800,600);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        ProdutoAdd produtoAdd = new ProdutoAdd();
        jif.add(produtoAdd);
        panel.add(jif);
    }//GEN-LAST:event_adicionarProdutoMenuItemActionPerformed

    private void listarProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutoMenuItemActionPerformed
        JInternalFrame jif = new JInternalFrame("Listar Produtos");
        jif.setSize(800,600);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        ProdutoList produtoList = new ProdutoList();
        jif.add(produtoList);
        panel.add(jif);
    }//GEN-LAST:event_listarProdutoMenuItemActionPerformed

    private void venderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderMenuItemActionPerformed
        JInternalFrame jif = new JInternalFrame("Executar Venda");
        jif.setSize(800,620);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        Venda venda = new Venda();
        jif.add(venda);
        panel.add(jif);
    }//GEN-LAST:event_venderMenuItemActionPerformed

    private void listaDeVendasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeVendasMenuItemActionPerformed
        JInternalFrame jif = new JInternalFrame("Lista de Vendas");
        jif.setSize(800,620);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        ListaDeVendas financeiro = new ListaDeVendas();
        jif.add(financeiro);
        panel.add(jif);
    }//GEN-LAST:event_listaDeVendasMenuItemActionPerformed

    private void fluxoDeCaixajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fluxoDeCaixajMenuItemActionPerformed
        JInternalFrame jif = new JInternalFrame("Fluxo de caixa");
        jif.setSize(800,620);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        FluxoDeCaixa fluxoDeCaixa = new FluxoDeCaixa();
        jif.add(fluxoDeCaixa);
        panel.add(jif);
    }//GEN-LAST:event_fluxoDeCaixajMenuItemActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void novoPagamentojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPagamentojMenuItemActionPerformed
        JInternalFrame jif = new JInternalFrame("Novo Pagamento");
        jif.setSize(600,300);
        jif.setLocation(0, 0);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        NovoPagamento novoPagamento = new NovoPagamento();
        jif.add(novoPagamento);
        panel.add(jif);
    }//GEN-LAST:event_novoPagamentojMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarClientes;
    private javax.swing.JMenuItem ListarClientes;
    private javax.swing.JMenuItem adicionarProdutoMenuItem;
    private javax.swing.JMenuItem fluxoDeCaixajMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listaDeVendasMenuItem;
    private javax.swing.JMenuItem listarProdutoMenuItem;
    private javax.swing.JMenuItem novoPagamentojMenuItem;
    private javax.swing.JDesktopPane panel;
    private javax.swing.JMenuItem venderMenuItem;
    // End of variables declaration//GEN-END:variables
}
