/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics_interface;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.PagamentoDAO;
import model.vo.Pagamento;
import util.DataConverter;

/**
 *
 * @author Gabriel
 */
public class NovoPagamento extends javax.swing.JPanel {

    /**
     * Creates new form ClienteListar
     */
    public NovoPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        descricaojLabel = new javax.swing.JLabel();
        descricaojLabel1 = new javax.swing.JLabel();
        valorjFormattedTextField = new javax.swing.JFormattedTextField();
        descricaojTextField = new javax.swing.JTextField();
        SalvarjButton = new javax.swing.JButton();
        descricaojLabel2 = new javax.swing.JLabel();
        tipoCombobox = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("NOVO PAGAMENTO");

        descricaojLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descricaojLabel.setText("Valor: ");

        descricaojLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descricaojLabel1.setText("Descriçao: ");

        SalvarjButton.setText("Salvar");
        SalvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButtonActionPerformed(evt);
            }
        });

        descricaojLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descricaojLabel2.setText("Tipo");

        tipoCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SalvarjButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descricaojLabel)
                                .addGap(18, 18, 18)
                                .addComponent(valorjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descricaojLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descricaojTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descricaojLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaojLabel1)
                    .addComponent(descricaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaojLabel2)
                    .addComponent(tipoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaojLabel)
                    .addComponent(valorjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(SalvarjButton)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButtonActionPerformed
        pagamento = new Pagamento();
        pagamento.setDescricao(descricaojTextField.getText());
        pagamento.setValor(Double.parseDouble(valorjFormattedTextField.getText()));
        pagamento.setData(new Date());
        pagamento.setTipo(tipoCombobox.getSelectedItem().toString().equalsIgnoreCase("Crédito")?Pagamento.CREDITO:Pagamento.DEBITO);
        
        PagamentoDAO pagamentoDAO = new PagamentoDAO();
        try {
            pagamentoDAO.salvar(pagamento);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Salvar!");
            Logger.getLogger(NovoPagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalvarjButtonActionPerformed

    private Pagamento pagamento;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalvarjButton;
    private javax.swing.JLabel descricaojLabel;
    private javax.swing.JLabel descricaojLabel1;
    private javax.swing.JLabel descricaojLabel2;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> tipoCombobox;
    private javax.swing.JFormattedTextField valorjFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
